name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t australia-southeast1-docker.pkg.dev/llm-hosting-458323/som-api/som-api:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push australia-southeast1-docker.pkg.dev/llm-hosting-458323/som-api/som-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy som-api \
            --image australia-southeast1-docker.pkg.dev/llm-hosting-458323/som-api/som-api:latest \
            --platform managed \
            --region australia-southeast1 \
            --min-instances 1 \
            --concurrency 1 \
            --allow-unauthenticated \
            --port 9000 \
